"""Transactional port for manual review commands; no concrete I/O dependencies."""

from typing import Any, Callable, Mapping, Protocol

from job_search_assistant.career.review import ReviewDraft
from job_search_assistant.career.store import ProfileVersionFacts
from job_search_assistant.career.types import CareerProfile
from job_search_assistant.core.audit import AuditEvent
from job_search_assistant.core.context import RequestContext


class ReviewTransaction(Protocol):
    def get_draft(self, draft_id: str) -> ReviewDraft: ...
    def find_draft(self, profile_id: str) -> ReviewDraft | None: ...
    def save_draft(self, draft: ReviewDraft, expected_version: int | None) -> None: ...
    def get_profile(self, profile_id: str) -> CareerProfile: ...
    def create_profile(self, profile: CareerProfile) -> None: ...
    def get_facts(self, version_id: str) -> ProfileVersionFacts:
        """Read committed immutable facts only; never write or rely on uncommitted data."""
    def require_document(self, document_id: str) -> None: ...
    def publish(self, profile: CareerProfile, facts: ProfileVersionFacts) -> None: ...
    def audit(self, event: AuditEvent) -> None: ...


class ReviewStore(Protocol):
    def get_review_draft(self, draft_id: str) -> ReviewDraft: ...
    def get_review_profile(self, profile_id: str) -> CareerProfile: ...
    def get_review_base_facts(self, version_id: str) -> ProfileVersionFacts: ...

    def execute_review_command(
        self, *, action: str, request: Mapping[str, Any], idempotency_key: str,
        context: RequestContext,
        operation: Callable[[ReviewTransaction], Mapping[str, Any]],
    ) -> dict[str, Any]:
        """Commit operation, audits and replay response together; rollback permits retry."""
